#!/bin/sh

set -e

. /usr/sbin/resin-vars

_vpn_port=443
readonly _vpn_port

if [ ! -f $CONFIG_PATH ]; then
	echo "prepare-openvpn: $CONFIG_PATH - No such file."
	exit 1
fi

# If the user api key exists we use it instead of the deviceApiKey as it means we haven't done the key exchange yet
_device_api_key=${PROVISIONING_API_KEY:-DEVICE_API_KEY}

if [ "$UUID" = "null" ] || [ "$_device_api_key" = "null" ]; then
	echo "prepare-openvpn: UUID and/or APIKEY missing from config file, VPN cannot connect"
	exit 1
fi

echo $UUID > /var/volatile/vpnfile
echo $_device_api_key >> /var/volatile/vpnfile
sed -e "/remote .*/ c\remote $VPN_ENDPOINT $_vpn_port" /etc/openvpn/resin.conf > /run/openvpn/resin.conf
